[alphavantage]
api_key = "WSFXHDXZK9N073TU"

[gemini]
api_key = "AIzaSyDX2Za-T4WMTS_ds7lkgvfYJxONne1HPHg"

[fred]
api_key = "a4300199dbf94251aad1aa0d84bef5f5"

[newsapi]
api_key = "eed1bf1ed6384ed7ba42b8d20ca346c1"
